# Do not modify this file! It was generated by `nixos-generate-config` for the
# current VMware installation. Regenerate it when the disk layout changes.
{
  lib,
  ...
}:

{
  boot.initrd.availableKernelModules = [
    "ata_piix"
    "mptspi"
    "uhci_hcd"
    "ehci_pci"
    "ahci"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/34bc3603-33fb-4436-a5e9-d3f02984235f";
    fsType = "btrfs";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/34bc3603-33fb-4436-a5e9-d3f02984235f";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/34bc3603-33fb-4436-a5e9-d3f02984235f";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C3C8-1262";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/dc292002-ba48-4327-a6a7-e1deffaa700f"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
